// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBEBW5M-_IwmNU-KJW8xbBg92FDkBrTjc',
    appId: '1:1032068163352:web:056c6bd84442a6df08e06d',
    messagingSenderId: '1032068163352',
    projectId: 'mscosmatics-2b622',
    authDomain: 'mscosmatics-2b622.firebaseapp.com',
    storageBucket: 'mscosmatics-2b622.firebasestorage.app',
    measurementId: 'G-P5FX0DBV3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjdo_0BdYYX6nEeWDC9FdmSNm5Co8XdCQ',
    appId: '1:1032068163352:android:764e38ea03fc3a5208e06d',
    messagingSenderId: '1032068163352',
    projectId: 'mscosmatics-2b622',
    storageBucket: 'mscosmatics-2b622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDATUYI0nwQTiyGYTjDlE2ppJ-QkOjqFqw',
    appId: '1:1032068163352:ios:fabb1f21a47c687d08e06d',
    messagingSenderId: '1032068163352',
    projectId: 'mscosmatics-2b622',
    storageBucket: 'mscosmatics-2b622.firebasestorage.app',
    iosBundleId: 'com.example.msCosmatics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDATUYI0nwQTiyGYTjDlE2ppJ-QkOjqFqw',
    appId: '1:1032068163352:ios:fabb1f21a47c687d08e06d',
    messagingSenderId: '1032068163352',
    projectId: 'mscosmatics-2b622',
    storageBucket: 'mscosmatics-2b622.firebasestorage.app',
    iosBundleId: 'com.example.msCosmatics',
  );
}
